-- Your SQL goes here
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    color TEXT NOT NULL,
    backend_type TEXT NOT NULL,
    inbox_project INTEGER,
    team_inbox INTEGER,
    child_order INTEGER,
    is_deleted INTEGER,
    is_archived INTEGER,
    is_favorite INTEGER,
    shared INTEGER,
    view_style TEXT NOT NULL,
    sort_order INTEGER,
    parent_id TEXT NOT NULL,
    collapsed INTEGER,
    icon_style TEXT NOT NULL,
    emoji TEXT NOT NULL,
    show_completed INTEGER,
    description TEXT NOT NULL,
    due_date TEXT NOT NULL,
    inbox_section_hidded INTEGER,
    sync_id TEXT NOT NULL,
    source_id TEXT NOT NULL
);